### PR TITLE
Fixed a minor typo.

### PR DESCRIPTION
**Pull request by Ming-Yeung-Alfred-Meng**
Fixed a minor typo.

### CODE REVIEW

**Review by david-wei-01001 — APPROVED** [review]
Excellent!

**Comment by Sue-Tong** [comment]
nice

**Review by Coco505 — APPROVED** [review]

**Comment by david-wei-01001** [comment]
> nice

**Comment by david-wei-01001** [comment]
Sorry, my bad

**Review by Sue-Tong — APPROVED** [review]

**Pull request merged**
