### PR TITLE
Revert "Revert "Completing JavaDoc up to Presenter""

### PR DESCRIPTION
**Pull request by david-wei-01001**
The following is available for review
1.Change UserInfo to User and update corresponding references
2.use try-catch block to enclose codes so that test do not throw unnecessary Exceptions

### CODE REVIEW

**Comment by david-wei-01001** [comment]
Sorry for the previous unchecked merge. I have already reverted it. Now this is available for review

**Comment by david-wei-01001** [comment]
Also included is writing JavaDoc up to Presenter and resolve TODO

**Review by Ming-Yeung-Alfred-Meng — APPROVED** [review]
ok.

**Review by Arthursleeps16hrs — APPROVED** [review]
Seems good to me!

**Pull request merged**
