### PR TITLE
safely eliminate all the warnings and add some missing java doc and delete commented code

### PR DESCRIPTION
**Pull request by Sue-Tong**

### CODE REVIEW

**Review by Coco505 — APPROVED** [review]

**Review by Ming-Yeung-Alfred-Meng — APPROVED** [review]
Nice.

**Review by david-wei-01001 — COMMENTED** [review]
good

**Review by Arthursleeps16hrs — APPROVED** [review]
Great!

**Comment by nopespace** [comment]
interesting

**Pull request merged**
